%{
#include "hpp.hpp"
%}
%option noyywrap yylineno

S [\+\-]?
N [0-9]+
%%
#[^\n]*				{}						/* comment			*/

{N}[eE]{S}{N}		TOC(Num,NUM)			/* numbers			*/
{N}\.{N}			TOC(Num,NUM)
{N}					TOC(Num,NUM)

\+					TOC(Op,ADD)				/* operators		*/
\-					TOC(Op,SUB)
\*					TOC(Op,MUL)
\/					TOC(Op,DIV)
\^					TOC(Op,POW)

[a-zA-Z0-9_]+		TOC(Sym,SYM)			/* symbol			*/

[ \t\r\n]+			{}						/* drop spaces		*/
.					{yyerror("lexer");}		/* undetected char	*/

