(lambda (k)
((lambda (k)
((lambda (k)
((lambda (k)
(k "First")) (lambda (pv)
(read-number/suspend pv k))))
(lambda (lv)
((lambda (k)
((lambda (k)
(k "Second")) (lambda (pv)
(read-number/suspend pv k))))
(lambda (rv)
(k (+ lv rv)))))))
(lambda (ov)
(k (display ov)))))