%{
#include "hpp.hpp"
%}
%option noyywrap yylineno
S [\+\-]?
N [0-9]+
%%
#[^\n]*				{}
[ \t\r\n]+			{}

{N}[eE]{S}{N}		TOC(Num,NUM)
{N}\.{N}			TOC(Num,NUM)
{N}					TOC(Num,NUM)

\(					TOC(Op,LP)
\)					TOC(Op,RP)
\[					TOC(Op,LQ)
\]					TOC(Op,RQ)
\{					TOC(Op,LC)
\}					TOC(Op,RC)

\=					TOC(Op,EQ)
\@					TOC(Op,AT)
\,					TOC(Op,COMMA)
\:					TOC(Op,COLON)

\+					TOC(Op,ADD)
\*					TOC(Op,MUL)
\^					TOC(Op,POW)

[a-zA-Z0-9_]+		TOC(Sym,SYM)

.					{yyerror("lexer");}

