#define MODULE 	"cpp"
#define TITLE 	"Y script"
#define ABOUT 	".cpp language realization sample for PLAI/"
#define AUTHOR 	"Dmitry Ponyatov <dponyatov@gmail.com>"
#define LICENSE "GNU LesserGPL"
#define GITHUB 	"https://github.com/ponyatov/PLAI/tree/master/cpp/"
#define LOGO 	"logo.png"
