%{
#include "hpp.hpp"
%}
%option main noyywrap
S [\+\-]?
N [0-9]+
%%
#[^\n]*			{}						/* comment rule	*/

{S}{N}			 {cout<<Sym(yytext).head()<<endl; }
{S}{N}\.{N}		 {cout<<Sym(yytext).head()<<endl; }
{S}{N}[eE]{S}{N} {cout<<Sym(yytext).head()<<endl; }

\+				{cout<<Sym("plus",yytext).head()<<endl; }
\-				{cout<<Sym("minus",yytext).head()<<endl; }
\*				{cout<<Sym("mult",yytext).head()<<endl; }

[ \t\r\n]+		{}						/* drop spaces	*/
